version: "3.7"

services:
  worker:
    build: .
    init: true
    networks:
      zennet:
  nginx:
    build: load-balancer
    volumes:
      - lb-data:/etc/nginx/
    container_name: app-ac-portfolio-lb
    ports:
      - 8029:8000
    networks:
      zennet:
    depends_on:
      - worker
volumes:
  lb-data:
    name: "ac-portfolio-lb-volume"
networks:
  zennet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
          gateway: 192.168.90.1